### ISSUE TITLE
Feature Request: accept regional/national datasets

### ISSUE THREAD

**Issue by tiernanmartin** [UrbanInstitute/ui-equity-tool#1]
This is a really impressive tool! 

Have you considered adding the ability to analyze datasets that are larger (geographically speaking) than a single municipality? Personally, I would love to be able to explore the distributional equity of regional and national data with this tool—if it had that ability. I tried uploading a national dataset (~4.5 million points) just to see what would happen, and the tool basically just selected the rows from one random city and dropped everything else (see the screenshot below).

Would it be possible to add regional/national analysis capabilities at some point?

Thanks!

<details>
 <summary>Click to expand image</summary>

![image](https://user-images.githubusercontent.com/8197328/94385745-beed9f80-00fa-11eb-917f-223dc44951d3.png)

</details>

**Comment by ajjitn** [comment]
Thanks for the kind words! This is definitely a highly requested feature and one we will be considering for v2 of the tool (given funding constraints). We have heard from folks that having the tool work at the following geographic levels would be helpful:

- county
- state
- national

Of the above, which ones do you think would be most useful for your use cases?

**Comment by tiernanmartin** [comment]
The [organization](http://www.futurewise.org/home) I work for frequently supports county government staff, so the county geography would have the highest priority if I had to choose just one of the three. That said, state-level analysis would also be a helpful benchmark for comparison. The national geography is the lowest priority for my use case, although it too could be useful for comparative analyses.

Best of luck with the development and funding of v2!

**Comment by alenastern** [comment]
Hey @tiernanmartin - this is approximately two years late, but I was looking back at issues on this repo today and wanted to make sure you'd seen [v2 of the Spatial Equity Data Tool ](https://apps.urban.org/features/equity-data-tool/) which incorporates County, State, and National level analyses. We still don't support regional level analyses but that's something that is still on the radar for a future update. Please let us know if you have any feedback on the new version!
